// Metadata index for Lenny's knowledge base
// Sourced from lennysdata MCP server — 10 newsletters + 51 podcasts
// Each entry maps to a real file in the MCP archive

export const METADATA_INDEX = [
  // ─── Newsletters ───────────────────────────────────────────
  {
    id: "pm-second-brain",
    title: "How to build your PM second brain with ChatGPT",
    source: "Lenny's Newsletter",
    guest: null,
    topics: ["ai", "product-management", "leadership", "strategy"],
    readTime: 10,
    published: "2025-12-16",
    filename: "newsletters/how-to-build-your-pm-second-brain-with-chatgpt.md",
    socialLabel: "Use AI to amplify your craft",
    sourceUrl: "https://www.lennysnewsletter.com/p/how-to-build-your-pm-second-brain-with-chatgpt",
  },
  {
    id: "claude-code-more",
    title: "Everyone should be using Claude Code more",
    source: "Lenny's Newsletter",
    guest: null,
    topics: ["ai", "engineering", "career", "leadership"],
    readTime: 12,
    published: "2025-10-14",
    filename: "newsletters/everyone-should-be-using-claude-code-more.md",
    socialLabel: "50 ways non-technical people use it",
    sourceUrl: "https://www.lennysnewsletter.com/p/everyone-should-be-using-claude-code-more",
  },
  {
    id: "essential-reading-1",
    title: "Essential reading for product builders — part 1",
    source: "Lenny's Newsletter",
    guest: null,
    topics: ["leadership", "strategy", "startups", "career"],
    readTime: 9,
    published: "2025-07-15",
    filename: "newsletters/essential-reading-for-product-builders-part-1.md",
    socialLabel: "7 timeless essays",
    sourceUrl: "https://www.lennysnewsletter.com/p/essential-reading-for-product-builders-part-1",
  },
  {
    id: "vibe-coding",
    title: "What people are vibe coding (and actually using)",
    source: "Lenny's Newsletter",
    guest: null,
    topics: ["ai", "engineering", "design", "career"],
    readTime: 14,
    published: "2025-07-08",
    filename: "newsletters/what-people-are-vibe-coding-and-actually-using.md",
    socialLabel: "50+ examples to inspire you",
    sourceUrl: "https://www.lennysnewsletter.com/p/what-people-are-vibe-coding-and-actually-using",
  },
  {
    id: "ai-glossary",
    title: "An AI glossary",
    source: "Lenny's Newsletter",
    guest: null,
    topics: ["ai", "engineering", "design"],
    readTime: 10,
    published: "2025-06-24",
    filename: "newsletters/an-ai-glossary.md",
    socialLabel: "AI terms explained simply",
    sourceUrl: "https://www.lennysnewsletter.com/p/an-ai-glossary",
  },
  {
    id: "pm-job-market-2025",
    title: "State of the product job market in 2025",
    source: "Lenny's Newsletter",
    guest: null,
    topics: ["product-management", "ai", "career", "strategy"],
    readTime: 5,
    published: "2025-05-13",
    filename: "newsletters/state-of-the-product-job-market-in-2025.md",
    socialLabel: "A lot to be optimistic about",
    sourceUrl: "https://www.lennysnewsletter.com/p/state-of-the-product-job-market-in-2025",
  },
  {
    id: "pm-guide-evals",
    title: "Beyond vibe checks: A PM's complete guide to evals",
    source: "Lenny's Newsletter",
    guest: null,
    topics: ["ai", "engineering", "leadership", "analytics"],
    readTime: 11,
    published: "2025-04-08",
    filename: "newsletters/beyond-vibe-checks-a-pms-complete-guide-to-evals.md",
    socialLabel: "The skill that makes or breaks AI products",
    sourceUrl: "https://www.lennysnewsletter.com/p/beyond-vibe-checks-a-pms-complete-guide-to-evals",
  },
  {
    id: "ai-prototyping",
    title: "A guide to AI prototyping for product managers",
    source: "Lenny's Newsletter",
    guest: null,
    topics: ["ai", "engineering", "design", "product-management"],
    readTime: 13,
    published: "2025-01-07",
    filename: "newsletters/a-guide-to-ai-prototyping-for-product-managers.md",
    socialLabel: "Idea to prototype in minutes",
    sourceUrl: "https://www.lennysnewsletter.com/p/a-guide-to-ai-prototyping-for-product-managers",
  },
  {
    id: "pm-unfair-role",
    title: "Product manager is an unfair role. So work unfairly.",
    source: "Lenny's Newsletter",
    guest: null,
    topics: ["leadership", "product-management", "organization", "ai"],
    readTime: 13,
    published: "2024-11-12",
    filename: "newsletters/product-manager-is-an-unfair-role-so-work-unfairly.md",
    socialLabel: "Thrive in the great flattening",
    sourceUrl: "https://www.lennysnewsletter.com/p/product-manager-is-an-unfair-role-so-work-unfairly",
  },
  {
    id: "duolingo-growth",
    title: "How Duolingo reignited user growth",
    source: "Lenny's Newsletter",
    guest: null,
    topics: ["growth", "strategy", "analytics", "design"],
    readTime: 14,
    published: "2023-02-28",
    filename: "newsletters/how-duolingo-reignited-user-growth.md",
    socialLabel: "350% growth acceleration story",
    sourceUrl: "https://www.lennysnewsletter.com/p/how-duolingo-reignited-user-growth",
  },

  // ─── Podcasts ──────────────────────────────────────────────
  {
    id: "jessica-fain",
    title: "The art of influence: The single most important skill that AI can't replace",
    source: "Lenny's Podcast",
    guest: "Jessica Fain",
    topics: ["leadership", "product-management", "career", "ai"],
    readTime: 45,
    published: "2026-03-22",
    filename: "podcasts/jessica-fain.md",
    socialLabel: "The skill AI can't replace",
    sourceUrl: "https://www.lennysnewsletter.com/p/jessica-fain",
  },
  {
    id: "claire-vo",
    title: "From skeptic to true believer: How OpenClaw changed my life",
    source: "Lenny's Podcast",
    guest: "Claire Vo",
    topics: ["ai", "engineering", "design", "leadership", "career"],
    readTime: 50,
    published: "2026-03-29",
    filename: "podcasts/claire-vo.md",
    socialLabel: "From skeptic to AI evangelist",
    sourceUrl: "https://www.lennysnewsletter.com/p/claire-vo",
  },
  {
    id: "jenny-wen",
    title: "How designers and engineers keep up with AI",
    source: "Lenny's Podcast",
    guest: "Jenny Wen",
    topics: ["design", "ai", "engineering", "strategy"],
    readTime: 40,
    published: "2026-03-01",
    filename: "podcasts/jenny-wen.md",
    socialLabel: "Keeping up with the AI pace",
    sourceUrl: "https://www.lennysnewsletter.com/p/jenny-wen",
  },
  {
    id: "jeetu-patel",
    title: "What's happening in the AI industry and how to make the most of it",
    source: "Lenny's Podcast",
    guest: "Jeetu Patel",
    topics: ["ai", "leadership", "engineering", "b2b"],
    readTime: 42,
    published: "2026-02-26",
    filename: "podcasts/jeetu-patel.md",
    socialLabel: "Industry insider perspective",
    sourceUrl: "https://www.lennysnewsletter.com/p/jeetu-patel",
  },
  {
    id: "boris-cherny",
    title: "The next big shift in how software is written",
    source: "Lenny's Podcast",
    guest: "Boris Cherny",
    topics: ["engineering", "ai", "leadership", "growth"],
    readTime: 50,
    published: "2026-02-19",
    filename: "podcasts/boris-cherny.md",
    socialLabel: "The future of software",
    sourceUrl: "https://www.lennysnewsletter.com/p/boris-cherny",
  },
  {
    id: "brian-halligan",
    title: "Why it's never been easier to start a company, and never been harder to scale one",
    source: "Lenny's Podcast",
    guest: "Brian Halligan",
    topics: ["startups", "leadership", "career", "b2b"],
    readTime: 38,
    published: "2026-02-15",
    filename: "podcasts/brian-halligan.md",
    socialLabel: "Sequoia CEO coach wisdom",
    sourceUrl: "https://www.lennysnewsletter.com/p/brian-halligan",
  },
  {
    id: "lazar-jovanovic",
    title: "The rise of the professional vibe coder",
    source: "Lenny's Podcast",
    guest: "Lazar Jovanovic",
    topics: ["ai", "engineering", "design", "career"],
    readTime: 47,
    published: "2026-02-08",
    filename: "podcasts/lazar-jovanovic.md",
    socialLabel: "A new AI-era job",
    sourceUrl: "https://www.lennysnewsletter.com/p/lazar-jovanovic",
  },
  {
    id: "dr-becky-kennedy",
    title: "A child psychologist's guide to working with difficult adults",
    source: "Lenny's Podcast",
    guest: "Dr. Becky Kennedy",
    topics: ["leadership", "design", "strategy"],
    readTime: 50,
    published: "2026-02-01",
    filename: "podcasts/dr-becky-kennedy.md",
    socialLabel: "Unexpectedly practical",
    sourceUrl: "https://www.lennysnewsletter.com/p/dr-becky-kennedy",
  },
  {
    id: "marc-andreessen",
    title: "The real AI boom hasn't even started yet",
    source: "Lenny's Podcast",
    guest: "Marc Andreessen",
    topics: ["ai", "startups", "engineering", "growth"],
    readTime: 58,
    published: "2026-01-29",
    filename: "podcasts/marc-andreessen.md",
    socialLabel: "Most shared this quarter",
    sourceUrl: "https://www.lennysnewsletter.com/p/marc-andreessen",
  },
  {
    id: "jason-cohen",
    title: "5 questions to ask when your product stops growing",
    source: "Lenny's Podcast",
    guest: "Jason Cohen",
    topics: ["growth", "strategy", "startups", "pricing"],
    readTime: 55,
    published: "2026-01-25",
    filename: "podcasts/jason-cohen.md",
    socialLabel: "2x unicorn founder's framework",
    sourceUrl: "https://www.lennysnewsletter.com/p/jason-cohen",
  },
  {
    id: "zevi-arnovitz",
    title: "The non-technical PM's guide to building with Cursor",
    source: "Lenny's Podcast",
    guest: "Zevi Arnovitz",
    topics: ["ai", "engineering", "product-management"],
    readTime: 38,
    published: "2026-01-18",
    filename: "podcasts/zevi-arnovitz.md",
    socialLabel: "Build real products without code",
    sourceUrl: "https://www.lennysnewsletter.com/p/zevi-arnovitz",
  },
  {
    id: "sam-lessin",
    title: "Silicon Valley's missing etiquette playbook",
    source: "Lenny's Podcast",
    guest: "Sam Lessin",
    topics: ["startups", "career", "leadership"],
    readTime: 50,
    published: "2026-01-15",
    filename: "podcasts/sam-lessin.md",
    socialLabel: "Show up with a low heart rate",
    sourceUrl: "https://www.lennysnewsletter.com/p/sam-lessin",
  },
  {
    id: "alexander-embiricos",
    title: "The power user's guide to Codex",
    source: "Lenny's Podcast",
    guest: "Alexander Embiricos",
    topics: ["engineering", "ai", "leadership", "startups"],
    readTime: 45,
    published: "2026-01-12",
    filename: "podcasts/alexander-embiricos.md",
    socialLabel: "Advanced context engineering",
    sourceUrl: "https://www.lennysnewsletter.com/p/alexander-embiricos",
  },
  {
    id: "molly-graham",
    title: "The high-growth handbook: Frameworks for leading through chaos",
    source: "Lenny's Podcast",
    guest: "Molly Graham",
    topics: ["startups", "career", "growth", "leadership"],
    readTime: 46,
    published: "2026-01-04",
    filename: "podcasts/molly-graham.md",
    socialLabel: "From Zuckerberg to Bret Taylor",
    sourceUrl: "https://www.lennysnewsletter.com/p/molly-graham",
  },
  {
    id: "jason-lemkin",
    title: "We replaced our sales team with 20 AI agents — here's what happened",
    source: "Lenny's Podcast",
    guest: "Jason Lemkin",
    topics: ["b2b", "startups", "leadership", "pricing"],
    readTime: 66,
    published: "2026-01-01",
    filename: "podcasts/jason-m-lemkin.md",
    socialLabel: "SaaStr's boldest experiment",
    sourceUrl: "https://www.lennysnewsletter.com/p/jason-m-lemkin",
  },
  {
    id: "matt-macinnis",
    title: "10 contrarian leadership truths every leader needs to hear",
    source: "Lenny's Podcast",
    guest: "Matt MacInnis",
    topics: ["leadership", "startups", "strategy", "career"],
    readTime: 47,
    published: "2025-12-28",
    filename: "podcasts/matt-macinnis.md",
    socialLabel: "Rippling CPO's playbook",
    sourceUrl: "https://www.lennysnewsletter.com/p/matt-macinnis",
  },
  {
    id: "elena-verna",
    title: "Making products more lovable through growth",
    source: "Lenny's Podcast",
    guest: "Elena Verna",
    topics: ["growth", "pricing", "strategy", "b2b"],
    readTime: 45,
    published: "2025-12-18",
    filename: "podcasts/elena-verna-40.md",
    socialLabel: "Growth meets lovability",
    sourceUrl: "https://www.lennysnewsletter.com/p/elena-verna-40",
  },
  {
    id: "edwin-chen",
    title: "The 100-person AI lab that became Anthropic and Google's secret weapon",
    source: "Lenny's Podcast",
    guest: "Edwin Chen",
    topics: ["ai", "pricing", "engineering", "startups"],
    readTime: 37,
    published: "2025-12-07",
    filename: "podcasts/edwin-chen.md",
    socialLabel: "$1B bootstrapped with <100 people",
    sourceUrl: "https://www.lennysnewsletter.com/p/edwin-chen",
  },
  {
    id: "tomer-cohen",
    title: "Why LinkedIn is turning PMs into AI-powered full stack builders",
    source: "Lenny's Podcast",
    guest: "Tomer Cohen",
    topics: ["ai", "leadership", "design", "startups"],
    readTime: 34,
    published: "2025-12-04",
    filename: "podcasts/tomer-cohen.md",
    socialLabel: "LinkedIn CPO's vision",
    sourceUrl: "https://www.lennysnewsletter.com/p/tomer-cohen",
  },
  {
    id: "jeanne-grosser",
    title: "What world-class GTM looks like in 2026",
    source: "Lenny's Podcast",
    guest: "Jeanne DeWitt Grosser",
    topics: ["strategy", "go-to-market", "b2b"],
    readTime: 40,
    published: "2025-11-30",
    filename: "podcasts/jeanne-grosser.md",
    socialLabel: "From Vercel, Stripe, Google",
    sourceUrl: "https://www.lennysnewsletter.com/p/jeanne-grosser",
  },
  {
    id: "stewart-butterfield",
    title: "Mental models for building products people love",
    source: "Lenny's Podcast",
    guest: "Stewart Butterfield",
    topics: ["design", "b2b", "leadership", "startups"],
    readTime: 50,
    published: "2025-11-20",
    filename: "podcasts/stewart-butterfield.md",
    socialLabel: "Slack founder's product wisdom",
    sourceUrl: "https://www.lennysnewsletter.com/p/stewart-butterfield",
  },
  {
    id: "dr-fei-fei-li",
    title: "The Godmother of AI on jobs, robots & why world models are next",
    source: "Lenny's Podcast",
    guest: "Dr. Fei-Fei Li",
    topics: ["ai", "strategy", "career"],
    readTime: 45,
    published: "2025-11-16",
    filename: "podcasts/dr-fei-fei-li.md",
    socialLabel: "Where AI is really heading",
    sourceUrl: "https://www.lennysnewsletter.com/p/dr-fei-fei-li",
  },
  {
    id: "grant-lee",
    title: "\"Dumbest idea I've heard\" to $100M ARR: Inside the rise of Gamma",
    source: "Lenny's Podcast",
    guest: "Grant Lee",
    topics: ["strategy", "growth", "startups", "design"],
    readTime: 42,
    published: "2025-11-13",
    filename: "podcasts/grant-lee.md",
    socialLabel: "From rejection to $100M",
    sourceUrl: "https://www.lennysnewsletter.com/p/grant-lee",
  },
  {
    id: "melanie-perkins",
    title: "How she built a $42B company from nothing",
    source: "Lenny's Podcast",
    guest: "Melanie Perkins",
    topics: ["design", "strategy", "startups", "leadership"],
    readTime: 50,
    published: "2025-11-02",
    filename: "podcasts/melanie-perkins.md",
    socialLabel: "The Canva story",
    sourceUrl: "https://www.lennysnewsletter.com/p/melanie-perkins",
  },
  {
    id: "chip-huyen",
    title: "AI Engineering 101",
    source: "Lenny's Podcast",
    guest: "Chip Huyen",
    topics: ["ai", "engineering", "design"],
    readTime: 38,
    published: "2025-10-23",
    filename: "podcasts/chip-huyen.md",
    socialLabel: "Nvidia, Stanford, Netflix",
    sourceUrl: "https://www.lennysnewsletter.com/p/chip-huyen",
  },
  {
    id: "robby-stein",
    title: "Inside Google's AI turnaround: The rise of AI Mode",
    source: "Lenny's Podcast",
    guest: "Robby Stein",
    topics: ["ai", "growth", "design", "strategy"],
    readTime: 40,
    published: "2025-10-10",
    filename: "podcasts/robby-stein.md",
    socialLabel: "VP of Product, Google Search",
    sourceUrl: "https://www.lennysnewsletter.com/p/robby-stein",
  },
  {
    id: "albert-cheng",
    title: "How to find hidden growth opportunities in your product",
    source: "Lenny's Podcast",
    guest: "Albert Cheng",
    topics: ["growth", "analytics", "design"],
    readTime: 38,
    published: "2025-10-05",
    filename: "podcasts/albert-cheng.md",
    socialLabel: "Duolingo, Grammarly, Chess.com",
    sourceUrl: "https://www.lennysnewsletter.com/p/albert-cheng",
  },
  {
    id: "ravi-mehta",
    title: "Why Tinder's CPO starts with JSON, not design",
    source: "Lenny's Podcast",
    guest: "Ravi Mehta",
    topics: ["ai", "leadership", "startups", "design"],
    readTime: 42,
    published: "2025-09-29",
    filename: "podcasts/ravi-mehta.md",
    socialLabel: "The secret to better AI prototypes",
    sourceUrl: "https://www.lennysnewsletter.com/p/ravi-mehta",
  },
  {
    id: "hamel-husain-shreya-shankar",
    title: "Why AI evals are the hottest new skill for product builders",
    source: "Lenny's Podcast",
    guest: "Hamel Husain & Shreya Shankar",
    topics: ["ai", "analytics", "engineering"],
    readTime: 40,
    published: "2025-09-25",
    filename: "podcasts/hamel-husain--shreya-shankar.md",
    socialLabel: "Creators of the #1 eval course",
    sourceUrl: "https://www.lennysnewsletter.com/p/hamel-husain-shreya-shankar",
  },
  {
    id: "ethan-smith",
    title: "How to get ChatGPT to recommend your product",
    source: "Lenny's Podcast",
    guest: "Ethan Smith",
    topics: ["ai", "go-to-market", "growth"],
    readTime: 38,
    published: "2025-09-14",
    filename: "podcasts/ethan-smith.md",
    socialLabel: "The ultimate guide to AEO",
    sourceUrl: "https://www.lennysnewsletter.com/p/ethan-smith",
  },
  {
    id: "ben-horowitz",
    title: "$46B of hard truths: Why founders fail and why you need to run toward fear",
    source: "Lenny's Podcast",
    guest: "Ben Horowitz",
    topics: ["leadership", "startups", "product-management"],
    readTime: 50,
    published: "2025-09-11",
    filename: "podcasts/ben-horowitz.md",
    socialLabel: "a16z co-founder speaks",
    sourceUrl: "https://www.lennysnewsletter.com/p/ben-horowitz",
  },
  {
    id: "scott-wu",
    title: "How Devin replaces junior engineers with infinite AI interns",
    source: "Lenny's Podcast",
    guest: "Scott Wu",
    topics: ["ai", "engineering", "startups"],
    readTime: 42,
    published: "2025-09-08",
    filename: "podcasts/scott-wu.md",
    socialLabel: "Cognition CEO's vision",
    sourceUrl: "https://www.lennysnewsletter.com/p/scott-wu",
  },
  {
    id: "howie-liu",
    title: "How we restructured Airtable's entire org for AI",
    source: "Lenny's Podcast",
    guest: "Howie Liu",
    topics: ["ai", "strategy", "leadership", "design"],
    readTime: 45,
    published: "2025-08-31",
    filename: "podcasts/howie-liu.md",
    socialLabel: "Airtable CEO's AI bet",
    sourceUrl: "https://www.lennysnewsletter.com/p/howie-liu",
  },
  {
    id: "asha-sharma",
    title: "Why agents will outnumber employees by 2026",
    source: "Lenny's Podcast",
    guest: "Asha Sharma",
    topics: ["ai", "engineering", "leadership"],
    readTime: 48,
    published: "2025-08-28",
    filename: "podcasts/asha-sharma.md",
    socialLabel: "Microsoft CVP of AI Platform",
    sourceUrl: "https://www.lennysnewsletter.com/p/asha-sharma",
  },
  {
    id: "eoghan-mccabe",
    title: "How Intercom rose from the ashes by betting everything on AI",
    source: "Lenny's Podcast",
    guest: "Eoghan McCabe",
    topics: ["ai", "pricing", "startups", "design"],
    readTime: 45,
    published: "2025-08-21",
    filename: "podcasts/eoghan-mccabe.md",
    socialLabel: "Intercom's AI reinvention",
    sourceUrl: "https://www.lennysnewsletter.com/p/eoghan-mccabe",
  },
  {
    id: "nick-turley",
    title: "Inside ChatGPT: The fastest-growing product in history",
    source: "Lenny's Podcast",
    guest: "Nick Turley",
    topics: ["ai", "design", "go-to-market"],
    readTime: 42,
    published: "2025-08-09",
    filename: "podcasts/nick-turley.md",
    socialLabel: "Head of ChatGPT at OpenAI",
    sourceUrl: "https://www.lennysnewsletter.com/p/nick-turley",
  },
  {
    id: "bret-taylor",
    title: "He saved OpenAI, invented the Like button, and built Google Maps",
    source: "Lenny's Podcast",
    guest: "Bret Taylor",
    topics: ["leadership", "design", "product-management"],
    readTime: 50,
    published: "2025-07-31",
    filename: "podcasts/bret-taylor.md",
    socialLabel: "Future of careers and agents",
    sourceUrl: "https://www.lennysnewsletter.com/p/bret-taylor",
  },
  {
    id: "madhavan-ramanujam",
    title: "Pricing your AI product: Lessons from 400+ companies",
    source: "Lenny's Podcast",
    guest: "Madhavan Ramanujam",
    topics: ["pricing", "strategy", "ai"],
    readTime: 46,
    published: "2025-07-27",
    filename: "podcasts/madhavan-ramanujam.md",
    socialLabel: "Includes 50 unicorns",
    sourceUrl: "https://www.lennysnewsletter.com/p/madhavan-ramanujam",
  },
  {
    id: "dan-shipper",
    title: "The AI-native startup: 5 products, 100% AI-written code",
    source: "Lenny's Podcast",
    guest: "Dan Shipper",
    topics: ["ai", "engineering", "startups"],
    readTime: 42,
    published: "2025-07-17",
    filename: "podcasts/dan-shipper.md",
    socialLabel: "7-figure revenue, fully AI-built",
    sourceUrl: "https://www.lennysnewsletter.com/p/dan-shipper",
  },
  {
    id: "benjamin-mann",
    title: "Anthropic co-founder on AGI timelines and AI safety",
    source: "Lenny's Podcast",
    guest: "Benjamin Mann",
    topics: ["ai", "engineering", "leadership", "strategy"],
    readTime: 34,
    published: "2025-07-20",
    filename: "podcasts/benjamin-mann.md",
    socialLabel: "Superintelligence by 2028?",
    sourceUrl: "https://www.lennysnewsletter.com/p/benjamin-mann",
  },
  {
    id: "sherwin-wu-v2",
    title: "Getting code into production in the AI era",
    source: "Lenny's Podcast",
    guest: "Sherwin Wu",
    topics: ["engineering", "ai", "leadership", "startups"],
    readTime: 40,
    published: "2026-02-12",
    filename: "podcasts/sherwin-wu-v2.md",
    socialLabel: "Engineering tradeoffs in AI",
    sourceUrl: "https://www.lennysnewsletter.com/p/sherwin-wu-v2",
  },
  {
    id: "aishwarya-reganti-kiriti-badam",
    title: "Building actionable feedback loops for AI products",
    source: "Lenny's Podcast",
    guest: "Aishwarya Naresh Reganti + Kiriti Badam",
    topics: ["ai", "leadership", "engineering", "go-to-market"],
    readTime: 42,
    published: "2026-01-11",
    filename: "podcasts/aishwarya-naresh-reganti--kiriti-badam.md",
    socialLabel: "AI feedback loops that work",
    sourceUrl: "https://www.lennysnewsletter.com/p/aishwarya-naresh-reganti-kiriti-badam",
  },
  {
    id: "jason-droege",
    title: "Scale AI CEO: $14B Meta deal and what frontier labs are building next",
    source: "Lenny's Podcast",
    guest: "Jason Droege",
    topics: ["ai", "startups", "strategy", "leadership"],
    readTime: 42,
    published: "2025-10-09",
    filename: "podcasts/jason-droege.md",
    socialLabel: "From Uber Eats to Scale AI",
    sourceUrl: "https://www.lennysnewsletter.com/p/jason-droege",
  },
  {
    id: "nicole-forsgren",
    title: "How to measure AI developer productivity in 2025",
    source: "Lenny's Podcast",
    guest: "Nicole Forsgren",
    topics: ["engineering", "leadership", "analytics", "strategy"],
    readTime: 36,
    published: "2025-10-19",
    filename: "podcasts/nicole-forsgren.md",
    socialLabel: "Creator of DORA and SPACE",
    sourceUrl: "https://www.lennysnewsletter.com/p/nicole-forsgren",
  },
  {
    id: "brendan-foody",
    title: "Why experts writing AI evals is creating the fastest-growing companies",
    source: "Lenny's Podcast",
    guest: "Brendan Foody",
    topics: ["ai", "strategy", "pricing", "startups"],
    readTime: 31,
    published: "2025-09-18",
    filename: "podcasts/brendan-foody.md",
    socialLabel: "$1M to $500M in 17 months",
    sourceUrl: "https://www.lennysnewsletter.com/p/brendan-foody",
  },
  {
    id: "rachel-lockett",
    title: "A guide to difficult conversations and building high-trust teams",
    source: "Lenny's Podcast",
    guest: "Rachel Lockett",
    topics: ["leadership", "career", "strategy"],
    readTime: 51,
    published: "2025-11-23",
    filename: "podcasts/rachel-lockett.md",
    socialLabel: "High-trust team building",
    sourceUrl: "https://www.lennysnewsletter.com/p/rachel-lockett",
  },
  {
    id: "jen-abel",
    title: "Sell the alpha, not the feature: Enterprise sales $1M to $10M ARR",
    source: "Lenny's Podcast",
    guest: "Jen Abel",
    topics: ["b2b", "startups", "strategy", "leadership"],
    readTime: 37,
    published: "2025-11-09",
    filename: "podcasts/jen-abel.md",
    socialLabel: "Enterprise sales playbook",
    sourceUrl: "https://www.lennysnewsletter.com/p/jen-abel",
  },
  {
    id: "dhanji-r-prasanna",
    title: "How Block is becoming the most AI-native enterprise in the world",
    source: "Lenny's Podcast",
    guest: "Dhanji R. Prasanna",
    topics: ["leadership", "engineering", "ai", "analytics"],
    readTime: 38,
    published: "2025-10-26",
    filename: "podcasts/dhanji-r-prasanna.md",
    socialLabel: "Block CTO's AI playbook",
    sourceUrl: "https://www.lennysnewsletter.com/p/dhanji-r-prasanna",
  },
  {
    id: "garrett-lord",
    title: "Inside the expert network training every frontier AI model",
    source: "Lenny's Podcast",
    guest: "Garrett Lord",
    topics: ["ai", "leadership", "strategy", "b2b"],
    readTime: 33,
    published: "2025-08-24",
    filename: "podcasts/garrett-lord.md",
    socialLabel: "Handshake CEO's AI pivot",
    sourceUrl: "https://www.lennysnewsletter.com/p/garrett-lord",
  },
  {
    id: "matt-lemay",
    title: "The one question that saves product careers",
    source: "Lenny's Podcast",
    guest: "Matt LeMay",
    topics: ["leadership", "product-management", "career"],
    readTime: 45,
    published: "2025-08-14",
    filename: "podcasts/matt-lemay.md",
    socialLabel: "Career-saving product advice",
    sourceUrl: "https://www.lennysnewsletter.com/p/matt-lemay",
  },
  {
    id: "chip-conley",
    title: "Brian Chesky's secret mentor on wisdom and succeeding in tech as you age",
    source: "Lenny's Podcast",
    guest: "Chip Conley",
    topics: ["leadership", "career", "startups"],
    readTime: 35,
    published: "2025-08-03",
    filename: "podcasts/chip-conley.md",
    socialLabel: "Founder of MEA, modern elder",
    sourceUrl: "https://www.lennysnewsletter.com/p/chip-conley",
  },
];

// Serendipity deck: curated daily picks grounded in real archive content
export const SERENDIPITY_PROMPTS = [
  {
    tag: "AI & Product",
    idea: "The best AI features feel like a colleague who anticipated your next question",
    sourceId: "pm-second-brain",
    question: "How can product managers use AI as a second brain?",
    socialLabel: "Use AI to amplify your craft",
  },
  {
    tag: "Growth",
    idea: "Duolingo's 350% growth came from leaderboards, streaks, and one powerful insight about gamification",
    sourceId: "duolingo-growth",
    question: "How did Duolingo reignite user growth?",
    socialLabel: "350% growth acceleration story",
  },
  {
    tag: "Leadership",
    idea: "Influence is the one skill AI will never replace — and most PMs underinvest in it",
    sourceId: "jessica-fain",
    question: "What is the most important skill AI can't replace?",
    socialLabel: "The skill AI can't replace",
  },
  {
    tag: "AI Strategy",
    idea: "The real AI boom hasn't started — we're still in the infrastructure phase",
    sourceId: "marc-andreessen",
    question: "What does Marc Andreessen think about where AI is heading?",
    socialLabel: "Most shared this quarter",
  },
  {
    tag: "Career",
    idea: "Product manager is an unfair role — the best PMs learn to work unfairly",
    sourceId: "pm-unfair-role",
    question: "How do top PMs thrive in the great flattening?",
    socialLabel: "Thrive in the great flattening",
  },
  {
    tag: "Building",
    idea: "Non-technical people are building real products with AI — and shipping them to users",
    sourceId: "vibe-coding",
    question: "What are people actually building with vibe coding?",
    socialLabel: "50+ examples to inspire you",
  },
  {
    tag: "Pricing",
    idea: "Most AI products are mispriced — the playbook from 400+ companies shows why",
    sourceId: "madhavan-ramanujam",
    question: "How should you price an AI product?",
    socialLabel: "Includes 50 unicorns",
  },
  {
    tag: "Startups",
    idea: "It's never been easier to start a company, and never been harder to scale one",
    sourceId: "brian-halligan",
    question: "What are the hardest challenges in scaling a startup today?",
    socialLabel: "Sequoia CEO coach wisdom",
  },
];

export function getSourceById(id) {
  return METADATA_INDEX.find(s => s.id === id) || null;
}

export function getDailyDeck() {
  const today = new Date().toISOString().split('T')[0];
  // Deterministic shuffle based on date
  const seed = today.split('-').reduce((a, b) => a + parseInt(b), 0);
  const shuffled = [...SERENDIPITY_PROMPTS].sort((a, b) => {
    const ha = (seed * 31 + a.sourceId.length) % 100;
    const hb = (seed * 31 + b.sourceId.length) % 100;
    return ha - hb;
  });
  return shuffled.slice(0, 3);
}
